const text = [
  `[1] Annos undeviginti natus exercitum privato consilio et privata impensa comparavi, per quem rem publicam a dominatione factionis oppressam in libertatem vindicavi. [Ob quae] senatus decretis honorificis in ordinem suum me adlegit, C. Pansa et A. Hirtio consulibus, consularem locum sententiae dicendae tribuens, et imperium mihi dedit. Res publica ne quid detrimenti caperet, me propraetore simul cum consulibus providere iussit. Populus autem eodem anno me consulem, cum cos. uterque bello cecidisset, et triumvirum rei publicae constituendae creavit.`,
  `[2] Qui parentem meum trucidaverunt, eos in exilium expuli iudiciis legitimis ultus eorum facinus, et postea bellum inferentis rei publicae vici bis acie.`,
  `[3] Bella terra et mari civilia externaque toto in orbe terrarum saepe gessi, victorque omnibus veniam petentibus civibus peperci. Externas gentes, quibus tuto ignosci potuit, conservare quam excidere malui. Millia civium Romanorum sub sacramento meo fuerunt circiter quingenta. Ex quibus deduxi in colonias aut remisi in municipia sua stipendis emeritis millia aliquanto plura quam trecenta, et iis omnibus agros adsignavi aut pecuniam pro praemiis militiae dedi. Naves cepi sescentas praeter eas, si quae minores quam triremes fuerunt.`,
  `[4] Bis ovans triumphavi, tris egi curulis triumphos et appellatus sum viciens et semel imperator. Cum autem pluris triumphos mihi senatus decrevisset, iis supersedi. Laurum de fascibus deposui in Capitolio, votis quae quoque bello nuncupaveram solutis. Ob res a me aut per legatos meos auspicis meis terra marique prospere gestas quinquagiens et quinquiens decrevit senatus supplicandum esse dis immortalibus. Dies autem, per quos ex senatus consulto supplicatum est, fuere DCCCLXXXX. In triumphis meis ducti sunt ante currum meum reges aut regum liberi novem. Consul fueram terdeciens, cum scribebam haec, et agebam septimum et tricensimum tribuniciae potestatis.`,
  `[5] Dictaturam et apsenti et praesenti mihi delatam et a populo et a senatu, M. Marcello et L. Arruntio consulibus non accepi. Non recusavi in summa frumenti penuria curationem annonae, quam ita administravi, ut intra paucos dies metu et periclo praesenti populum universum liberarem impensa et cura mea. Consulatum quoque tum annuum et perpetuum mihi delatum non recepi.`,
  `[6] Consulibus M. Vinicio et Q. Lucretio et postea P. Lentulo et Cn. Lentulo et tertium Paullo Fabio Maximo et Q. Tuberone senatu populoque Romano consentientibus ut curator legum et morum summa potestate solus crearer, nullum magistratum contra morem maiorum delatum recepi. Quae tum per me geri senatus voluit, per tribuniciam potestatem perfeci, cuius potestatis conlegam et ipse ultro quinquiens a senatu depoposci et accepi.`,
  `[7] Triumvirum rei publicae constituendae fui per continuos annos decem. Princeps senatus fui usque ad eum diem quo scripseram haec per annos quadraginta. Pontifex maximus, augur, XV virum sacris faciundis, VII virum epulonum, frater arvalis, sodalis Titius, fetialis fui.`,
  `[8] Patriciorum numerum auxi consul quintum iussu populi et senatus. Senatum ter legi, et in consulatu sexto censum populi conlega M. Agrippa egi. Lustrum post annum alterum et quadragensimum feci, quo lustro civium Romanorum censa sunt capita quadragiens centum millia et sexaginta tria millia. Tum iterum consulari cum imperio lustrum solus feci C. Censonno et C. Asinio cos., quo lustro censa sunt civium Romanorum capita quadragiens centum millia et ducenta triginta tria millia. Et tertium consulari cum imperio lustrum conlega Tib. Caesare filio meo feci Sex. Pompeio et Sex. Appuleio cos., quo lustro censa sunt civium Romanorum capitum quadragiens centum millia et nongenta triginta et septem millia. Legibus novis me auctore latis multa exempla maiorum exolescentia iam ex nostro saeculo reduxi et ipse multarum rerum exempla imitanda posteris tradidi.`,
  `[9] Vota pro valetudine mea suscipi per consules et sacerdotes quinto quoque anno senatus decrevit. Ex iis votis saepe fecerunt vivo me ludos aliquotiens sacerdotum quattuor amplissima collegia, aliquotiens consules. Privatim etiam et municipatim universi cives unanimiter continenter apud omnia pulvinaria pro valetudine mea supplicaverunt.`,
  `[10] Nomen meum senatus consulto inclusum est in saliare carmen, et sacrosanctus in perpetum ut essem et, quoad viverem, tribunicia potestas mihi esset, per legem sanctum est. Pontifex maximus ne fierem in vivi conlegae mei locum, populo id sacerdotium deferente mihi quod pater meus habuerat, recusavi. Quod sacerdotium aliquod post annos, eo mortuo qui civilis motus occasione occupaverat, cuncta ex Italia ad comitia mea confluente multitudine, quanta Romae nunquam fertur ante id tempus fuisse, recepi, P. Sulpicio C. Valgio consulibus.`,
];
export default text;
