const menu = [
    {
      id: 1,
      title: 'John Wick: Chapter 3 - Parabellum (2019)',
      category: 'Action',
      price: 15.99,
      img: './images/item-1.jpg',
      desc: `The third entry of the franchise sees John Wick (Keanu Reeves) on the run with a $14 million bounty placed on him after he kills a member of an underground assassin's guild. With every hitman in the world hot on his trail, he enlists the help of a trusted former colleague (Halle Berry) to fight his way out of New York City.`,
    },
    {
      id: 2,
      title: 'Avatar (2009)',
      category: 'Action',
      price: 13.99,
      img: './images/item-2.jpg',
      desc: `A paraplegic ex-marine finds a new life on the distant planet of Pandora, only to find himself battling humankind alongside the planet's indigenous Na'vi race in this ambitious digital 3D sci-fi epic from Academy Award-winning Titanic director James Cameron.`,
    },
    {
      id: 3,
      title: 'Dune (1984)',
      category: 'Action',
      price: 6.99,
      img: './images/item-3.jpg',
      desc: `David Lynch wades through dark waters in his adaptation of Frank Herbert's cult science fiction novel. In condensing Herbert's rambling and complex book by eliminating characters and compacting events, Lynch succeeds in rendering the story incomprehensible to those unfamiliar with the novel and making the film look like a sketchy greatest hits collection of the book for Herbert fans.`,
    },
    {
      id: 4,
      title: 'Evil Dead 2: Dead by Dawn (1987)',
      category: 'Horror',
      price: 20.99,
      img: './images/item-4.jpg',
      desc: `This high-octane semi-sequel to Sam Raimi's cult hit The Evil Dead has nearly eclipsed its predecessor's reputation thanks to an endless barrage of hyperkinetic camera acrobatics, rapid-fire editing and "splatstick" gore effects ... not to mention a truly goofy performance by Bruce Campbell. `,
    },
    {
      id: 5,
      title: 'Don\'t Breathe (2016)',
      category: 'Horror',
      price: 22.99,
      img: './images/item-5.jpg',
      desc: `Three friends (Dylan Minnette, Jane Levy, and Daniel Zovatto) plot to end their money woes by burglarizing the home of a blind recluse (Stephen Lang), but the heist quickly goes awry when they discover that their target is concealing a horrifying secret -- and that he isn't as harmless as they had thought.`,
    },
    {
      id: 6,
      title: 'House of Wax (2005)',
      category: 'Horror',
      price: 18.99,
      img: './images/item-6.jpg',
      desc: `A bunch of college students are stranded in a small town where suffering for art takes on a whole new meaning in this tale of terror. Carly (Elisha Cuthbert) and her boyfriend, Wade (Jared Padalecki), have hit the road with a handful of their friends to attend a championship college football game;`,
    },
    {
      id: 7,
      title: 'Split (2017)',
      category: 'Thriller',
      price: 8.99,
      img: './images/item-7.jpg',
      desc: `An outing takes a sinister turn for three teenage friends (Anya Taylor-Joy, Haley Lu Richardson, and Jessica Sula) when they are kidnapped by a ruthless stranger (James McAvoy) and imprisoned in his basement. They soon learn that their captor has multiple-personality disorder, forcing them to plot their escape without ever knowing which of his 23 personas -- young or old, male or female, benign or monstrous.`,
    },
    {
      id: 8,
      title: 'The Rock (1996)',
      category: 'Thriller',
      price: 12.99,
      img: './images/item-8.jpg',
      desc: `The sophomore film from former music video and commercial director Michael Bay, this fast-paced action yarn featured rapid-fire editing, a cutting-edge rock soundtrack and liberal use of shots awash in a haze of burnished hues, all trademarks of producers Don Simpson and Jerry Bruckheimer. Nicolas Cage stars as Stanley Goodspeed, an FBI chemical weapons expert handed a unique assignment.`,
    },
    {
      id: 9,
      title: 'Tenet (2020)',
      category: 'Thriller',
      price: 16.99,
      img: './images/item-9.jpg',
      desc: `In the not-so-distant future, innovative technologies reign supreme. As rival nations vie for global supremacy, the threat of a third World War is too great to ignore as tensions escalate. A special agent (John David Washington) and his partner (Robert Pattinson) agree to a risky new mission using the latest advancements in time travel and human evolution to put a stop to the cause of war at its source.`,

    },
  ];
  export default menu;